# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 14:17
from __future__ import unicode_literals

import address.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='address.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Debate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('public', models.BooleanField(default=True)),
                ('state', models.CharField(blank=True, choices=[['p', 'pending'], ('a', 'accepted'), ('r', 'refused')], default='p', max_length=1)),
                ('mduration', models.IntegerField(blank=True, default=60)),
                ('contact', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='debates', to='debate.Account')),
            ],
        ),
        migrations.CreateModel(
            name='ForbiddenEmail',
            fields=[
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('lon', models.FloatField(blank=True)),
                ('lat', models.FloatField(blank=True)),
                ('address', address.models.AddressField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='address.Address')),
                ('medias', models.ManyToManyField(blank=True, default=[], related_name='_organization_medias_+', to='debate.Media')),
                ('organizers', models.ManyToManyField(blank=True, default=[], related_name='organizations', to='debate.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('mduration', models.IntegerField(blank=True, default=60)),
                ('debate', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='debate.Debate')),
                ('organization', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedulings', to='debate.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('accounts', models.IntegerField()),
                ('debates', models.IntegerField()),
                ('organizations', models.IntegerField()),
                ('votes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('account', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='debate.Account')),
                ('debate', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='debate.Debate')),
            ],
        ),
        migrations.AddField(
            model_name='debate',
            name='medias',
            field=models.ManyToManyField(blank=True, default=[], related_name='_debate_medias_+', to='debate.Media'),
        ),
        migrations.AddField(
            model_name='category',
            name='debates',
            field=models.ManyToManyField(blank=True, to='debate.Debate'),
        ),
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='debate.Media'),
        ),
        migrations.AddField(
            model_name='account',
            name='languages',
            field=models.ManyToManyField(blank=True, default=[], related_name='_account_languages_+', to='address.Country'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('account', 'debate')]),
        ),
    ]
